#!/usr/bin/env python3
"""Verifier controls + real counting-backend selftests. ZERO Product runs."""
import copy,gzip,hashlib,json,struct,subprocess,tempfile
from pathlib import Path
import cases,fixtures as fx
from pcm import PCM
from oracle import Work,COUNTERS,check_render,require

checks=[];red=[]
def ok(name,fn):fn();checks.append(name)
def rejects(name,reason,fn):
    try:fn()
    except AssertionError as e:require(reason in str(e),'wrong rejection '+name+': '+str(e));red.append(name)
    else:raise AssertionError('control survived '+name)
def counters(**kw):d=dict.fromkeys(COUNTERS,0);d.update(kw);return d
def obs(**kw):return dict(result=0,more_work=False,counters=counters(),**kw)

cs=cases.cases();require(len({c['id'] for c in cs})==len(cs),'duplicate census')
require(len(set(c['row'] for c in cs))==3 and len(cs)>=25,'nontrivial tranche census')
for name in sorted(set(c['fixture'] for c in cs)):
    f=fx.make(name);fx.validate(f);meta=fx.metadata(f)
    require(len(meta[0])==512 and meta[0]==meta[f['block_count']-1],'superblock bytes/mirror')
    require(fx.crc(meta[0][:508])==struct.unpack_from('<I',meta[0],508)[0],'superblock CRC')
    for side,base in (('A',8),('B',264)):
        h=meta[base];raw=b''.join(struct.pack('<III',*e) for e in f['sides'][side])
        require(fx.crc(h[:60]+raw)==struct.unpack_from('<I',h,60)[0],'entry CRC')
        require(struct.unpack_from('<Q',h,20)[0]==fx.length(f,side),'entry total')
    checks.append('truthful-fixture-'+name)

require(fx.make('contiguous-158760000')['nominal']==3600,'C60 exact label')
N,T=1240313,19380
for b,want in zip((1,2,7,64,1024),(1240450,620225,193819,19383,19383)):
    c=min(b,64);require(T*fx.ceildiv(64,c)+fx.ceildiv(130,c)==want,'C60 callback math')
require((N+130)*512==635106816,'C60 requested bytes')
checks.append('five-C60-budget-ceilings')

f=fx.make('contiguous-40001');w=Work(1)
w.payload_blocks=fx.ceildiv(40001*4,512);w.payload_calls=fx.ceildiv(40001*4,32768)
w.counts['mapping_entry_visits']=4+4*w.payload_blocks+32
w.finish(40001*4,1024);checks.append('exact-boundary-positive')
bad=copy.deepcopy(w);bad.payload_blocks+=131
rejects('whole-window-reread','payload reread ceiling',lambda:bad.finish(40001*4))
bad=copy.deepcopy(w);bad.payload_calls=bad.payload_blocks
rejects('tiny-transfer','tiny-transfer callback ceiling',lambda:bad.finish(40001*4))
bad=Work(4096);bad.payload_blocks=8192;bad.counts['mapping_entry_visits']=4096*8192
require(4*4096+4*8192+32==49184,'max-E finite ceiling')
rejects('full-index-rescan','mapping visit ceiling',lambda:bad.finish())
bad=copy.deepcopy(w);bad.counts['retained_move_bytes']=1
rejects('retained-movement','retained monotone movement',lambda:bad.finish(40001*4))
bad=copy.deepcopy(w);bad.counts['refill_copy_bytes']=bad.payload_blocks*512+1
rejects('copy-amplification','PCM copy ceiling',lambda:bad.finish(40001*4))
rejects('count-not-callback-budget','service budget',lambda:Work(1).add({'fn':'tape_service','budget':1},obs(),[[1,2048,2,0,2]],f))
rejects('render-I/O','render I/O',lambda:Work(1).add({'fn':'tape_render','frames':1},obs(),[[1,2048,1,0,1]],f))
rejects('device-extent','device extent',lambda:Work(1).add({'fn':'tape_service','budget':2},obs(),[[1,f['block_count']-1,2,0,2]],f))
rejects('wrong-completion','completion classification',lambda:Work(1).add({'fn':'tape_service','budget':2},obs(),[[1,2048,2,1,1]],f))
idle=obs();idle['counters']['idle_loop_iterations']=9
rejects('idle-nine-loops','idle loop ceiling',lambda:Work(1).add({'fn':'tape_service','budget':1},idle,[],f,idle=True))
idle=obs();idle['counters']['mapping_entry_visits']=1
rejects('idle-mapping','idle PCM/mapping work',lambda:Work(1).add({'fn':'tape_service','budget':1},idle,[],f,idle=True))
idle=obs();idle['counters']['refill_copy_bytes']=1
rejects('idle-copy','idle PCM/mapping work',lambda:Work(1).add({'fn':'tape_service','budget':1},idle,[],f,idle=True))
seek=obs();seek['counters']['mapping_entry_visits']=35
rejects('seek-visit-overrun','seek visit ceiling',lambda:Work(1).add({'fn':'tape_seek'},seek,[],f))
delta=counters();delta['mapping_entry_visits']=2**64
seek=obs();seek['counters']=delta
rejects('counter-wrap','wide nonnegative',lambda:Work(1).add({'fn':'tape_seek'},seek,[],f))
checks.append('event-budget-classification-and-work-controls')

# Literal vectors independently specify sample phase, floor, reverse snap and
# endpoint flags; they are not generated by a synthetic Product adapter.
def small(samples,rate,at=0):
    f=fx.make('contiguous-'+str(len(samples)));m=PCM(f,'B',at)
    m.timeline_override=b''.join(struct.pack('<hh',x,-x) for x in samples)
    m.set_rate(rate);return m
m=small([0,1000,2000],-65536,3)
require(m.render(9)==struct.pack('<hhhhhh',2000,-2000,1000,-1000,0,0),'reverse snap/zero frame')
require(m.start and not m.end,'reverse endpoint flags');checks.append('literal-reverse-snap')
m=small([0,1000,2000],32768)
require(m.render(6)==b''.join(struct.pack('<hh',x,-x) for x in [0,500,1000,1500,2000,2000]),'fractional floor/final hold')
checks.append('literal-fractional-final-frame')
m=small([0,-1],32768);require(struct.unpack('<hhhh',m.render(2))==(0,0,-1,0),'negative difference floors')
checks.append('literal-negative-floor')
for rate in (2147483647,-2147483648):
    m=small([17],rate,1 if rate<0 else 0);require(m.render(9)==struct.pack('<hh',17,-17),'extreme one-frame clamp')
checks.append('int32-extreme-single-frame')
m=small([0,1000,2000],65536);o={'result':0,'rendered':1,'pcm_hex':'00000000',
                              'position_frame':1,'at_start':False,'at_end':False}
check_render(m,{'frames':1},o,complete=True);checks.append('positive-exact-render-verdict')
m=small([0,1000,2000],65536);bad=copy.deepcopy(o);bad['pcm_hex']='01000000'
rejects('stale-warm-side-content','exact PCM',lambda:check_render(m,{'frames':1},bad))
m=small([0,1000,2000],65536)
rejects('invalidated-ring','invalidated ring',lambda:check_render(m,{'frames':1},o,zero=True))
m=small([0,1000,2000],32768,1);m.pos|=1<<31
bad={'result':0,'rendered':1,'pcm_hex':struct.pack('<hh',1000,-1000).hex(),
     'position_frame':2,'at_start':False,'at_end':False}
rejects('missing-lookahead','exact PCM',lambda:check_render(m,{'frames':1},bad))

# Actual C backend: generated samples, writes overriding generated data, failure
# poison, partial-failure prefix, out-of-extent handling and request trace counts.
HERE=Path(__file__).resolve().parent
with tempfile.TemporaryDirectory() as tmp:
    p=Path(tmp);ff=fx.make('contiguous-129');fx.write(ff,p/'meta.img')
    driver=p/'device_test.c';driver.write_text(r'''
#include "counting_device.h"
#include <stdlib.h>
#include <string.h>
int main(int argc,char **argv) {
 read1_device d;unsigned char b[1024],x[512];(void)argc;
 if(read1_open(&d,argv[1],argv[2],(uint32_t)strtoul(argv[3],0,10),0,0))return 1;
 if(read1_read(&d,2048,2,b))return 2;
 FILE *f=fopen(argv[4],"wb");if(!f)return 3;
 if(fwrite(b,1,1024,f)!=1024)return 4;
 fclose(f);
 memset(x,0x42,512);if(read1_write(&d,2048,1,x)||read1_flush(&d))return 5;
 if(read1_read(&d,2048,1,b)||memcmp(x,b,512))return 6;
 d.fail_read=1;d.fail_read_prefix=1;
 if(!read1_read(&d,2048,2,b)||memcmp(x,b,512)||b[512]!=0xcd)return 7;
 if(!read1_read(&d,d.blocks-1,2,b))return 8;
 d.fail_flush=1;if(!read1_flush(&d))return 9;
 read1_close(&d);return 0;
}
''')
    subprocess.run(['cc','-std=c99','-Wall','-Wextra','-Werror','-I',str(HERE),str(driver),str(HERE/'counting_device.c'),'-o',str(p/'test')],check=True)
    subprocess.run([str(p/'test'),str(p/'meta.img'),str(p/'trace'),str(ff['block_count']),str(p/'pcm')],check=True)
    require((p/'pcm').read_bytes()==fx.block(ff,2048)+fx.block(ff,2049),'C/Python fixture bytes')
    trace=list(struct.iter_unpack('<IIIII',(p/'trace').read_bytes()))
    require(trace==[(1,2048,2,0,2),(2,2048,1,0,1),(3,0,0,0,0),(1,2048,1,0,1),
                    (1,2048,2,1,0),(1,ff['block_count']-1,2,1,0),(3,0,0,1,0)],'actual counting trace')
checks.append('actual-C-counting-backend-with-partial-error-control')

# Exercise the actual runner/replay schedule without claiming Product execution.
from runner import run_case,canonical
import io
with tempfile.TemporaryDirectory() as tmp:
    c=next(c for c in cs if c['id']=='cold-1-b1024');f=fx.make(c['fixture'])
    ident=hashlib.sha256(canonical(f).encode()).hexdigest()
    records=[]
    def record(command,observation,events=()):
        records.append(canonical({'case':c['id'],'command':command,'observation':observation,'events':list(events)})+'\n')
    record({'fn':'init','fixture':f,'fixture_sha256':ident,'writable':False,'play_ring_len':65536,'rec_ring_len':65536},
           dict(result=0,write_callback_null=True))
    record({'fn':'tape_mount','side':'A','resume':0,'warm':None},obs())
    record({'fn':'tape_set_rate','rate':65536},obs())
    o=obs();o['counters']['refill_copy_bytes']=512;o['counters']['mapping_entry_visits']=1
    record({'fn':'tape_service','budget':1024},o,[[1,2048,1,0,1]])
    record({'fn':'tape_render','frames':1},dict(result=0,rendered=1,pcm_hex=fx.frame(f,'A',0).hex(),
           position_frame=1,at_start=False,at_end=True,counters=counters()))
    record({'fn':'tape_service','budget':1024},obs())
    record({'fn':'tape_render','frames':1},dict(result=0,rendered=0,pcm_hex='',position_frame=1,
           at_start=False,at_end=True,counters=counters()))
    record({'fn':'tape_unmount'},dict(result=0,position_frame=1,counters=counters()))
    source=''.join(records)
    run_case(c,None,tmp,io.StringIO(),reader=io.StringIO(source));checks.append('canonical-streaming-replay')
    wrong=json.loads(records[3]);wrong['command']['budget']=64
    changed=''.join(records[:3])+canonical(wrong)+'\n'+''.join(records[4:])
    rejects('schedule-spoof','canonical schedule mismatch',lambda:run_case(c,None,tmp,io.StringIO(),reader=io.StringIO(changed)))
    rejects('missing-observation','missing replay call',lambda:run_case(c,None,tmp,io.StringIO(),reader=io.StringIO(''.join(records[:-1]))))

# Gate controls: synthetic/incomplete/misbound observations must not qualify.
from qualification import qualify
with tempfile.TemporaryDirectory() as tmp:
    rr=Path(tmp)/'run';cr=Path(tmp)/'control';rr.mkdir();cr.mkdir()
    commit,tree='a'*40,'b'*40
    run={'schema':'read1-run-v1','kind':'synthetic','product_commit':commit,'engine_tree':tree}
    ctrl={'schema':'read1-controls-v1','kind':'actual-Product-control-run','product_commit':commit,'engine_tree':tree}
    (rr/'manifest.json').write_text(json.dumps(run));(cr/'manifest.json').write_text(json.dumps(ctrl))
    rejects('synthetic-cannot-qualify','actual Product run',lambda:qualify(rr,cr,commit,tree))
    run.update(kind='actual-Product-observations',adapter_sha256='d'*64,
               complete_case_census=False,shipping_equivalence_executed=False)
    ctrl['adapter_sha256']='d'*64
    (rr/'manifest.json').write_text(json.dumps(run));(cr/'manifest.json').write_text(json.dumps(ctrl))
    rejects('incomplete-cannot-qualify','full census',lambda:qualify(rr,cr,commit,tree))
    ctrl['engine_tree']='c'*40;(cr/'manifest.json').write_text(json.dumps(ctrl))
    rejects('wrong-head-cannot-qualify','exact candidate/engine',lambda:qualify(rr,cr,commit,tree))

# Actual compiler probe verifies all three absence layers and the leaked-site gate.
# This is a verifier-owned toy translation unit, NOT a Product shipping build.
from absence import inspect
from runner import file_sha
with tempfile.TemporaryDirectory() as tmp:
    p=Path(tmp)
    for leaked in (False,True):
        root=p/('leak' if leaked else 'clean');root.mkdir();src=root/'probe.c'
        src.write_text('volatile unsigned long tape_read1_counter_leaked=1;\nint main(void){return (int)++tape_read1_counter_leaked;}\n'
                       if leaked else 'int main(void){return 0;}\n')
        subprocess.run(['cc','-std=c99','-E','-P',str(src),'-o',str(root/'preprocess.txt')],check=True)
        subprocess.run(['cc','-std=c99','-c',str(src),'-o',str(root/'probe.o')],check=True)
        with (root/'object.txt').open('w') as out:subprocess.run(['nm','-a',str(root/'probe.o')],check=True,stdout=out)
        subprocess.run(['cc',str(root/'probe.o'),'-Wl,-Map='+str(root/'link.txt'),'-o',str(root/'probe')],check=True)
        exit_status=subprocess.run([str(root/'probe')]).returncode
        require(exit_status==(2 if leaked else 0),'actual probe control work')
        m={'kind':'actual-deliberate-shipping-leak' if leaked else 'actual-shipping-absence',
           'product_commit':'verifier-only','engine_tree':'verifier-only','translation_units':['probe.c'],
           'layers':{k:[{'file':k+'.txt','sha256':file_sha(root/(k+'.txt'))}] for k in ('preprocess','object','link')}}
        (root/'manifest.json').write_text(json.dumps(m))
        inspect(root/'manifest.json','verifier-only','verifier-only',leaked)
    checks.append('actual-compiler-three-layer-absence-probe')
    m['kind']='actual-shipping-absence';(p/'leak'/'manifest.json').write_text(json.dumps(m))
    rejects('shipping-leak','shipping observation seam leak',lambda:inspect(p/'leak'/'manifest.json','verifier-only','verifier-only'))
print(json.dumps({'kind':'verifier-selftest-not-Product','checks':checks,'red_controls':red,
                  'canonical_cases':len(cs),'meaningful_rows':3,'actual_Product_runs':0},indent=2))
